
// ------- Recommendations

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  CodeSystem:  CsRecomandationPcsp
  Id: cs-recommendation-eu-pcsp
  Title: "PCSP Recommendations"
  Description:  "Recommendations proposed by the PCSP algorithm"
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

* #1 "Perform appropriate thyroid screening from the fifth year after the end of radiotherapy. Discuss with your doctor whether to schedule: Clinical thyroid examination every 1-2 years; or Thyroid ultrasound every 3-5 years." "Subsequent thyroid cancer"
* #2 "Perform Mammography and Breast magnetic resonance imaging (MRI) should be performed annually from the eighth year after the end of radiotherapy, but not before the age of 25. These examinations should be continued until at least age 60." "Subsequent breast cancer"
* #3 "Perform: Cardiological evaluation at the end of treatment and every 2-3 years thereafter; Electrocardiogram (ECG) at the end of treatment, to be repeated at the age of 18 and cardiological evaluation in case of palpitations, dizziness and/or fainting/loss of consciousness. Echocardiogram 2 years after the end of treatment, to be repeated every 2-3 years; If female, echocardiogram in the first trimester of pregnancy." "Cardiac problems (Cardiomyopathy and/or Valvular disease and/or Cardiac ischemia)"
* #4 "Perform a spermiogram once the process of puberty is complete (if desired and if the patient wants to evaluate possibility to have children in the future)." "Impaired fertility Impaired spermatogenesis"
* #5 "During the stages of puberty: Perform annual clinical check-ups (if clinically necessary, every six months) in order to assess growth rate and pubertal development. Once the process of puberty is complete: Test testosterone levels early in the morning every 2-3 years. If this is not possible, perform LH blood dosage." "Testosterone deficiency"
* #6 "An andrological examination should be performed if symptoms attributable to sexual dysfunction appear." "Physical sexual dysfunction"
* #7 "In girls: Perform at least once a year a clinical check-up to assess height, weight and pubertal development (breast growth). In case of abnormal or no pubertal development, check FSH and 17betaestradiol levels. In women who have already had their first menstrual cycle: Monitor the regularity of menstrual cycles. In case of irregular cycles (less than 21 days or more than 35 days) or if you have not had a cycle for at least 4 months, we recommend a blood test for FSH and estradiol and an endocrine/gynaecological check-up. These examinations are also recommended if you wish to find out about your fertility status." "Premature ovarian insufficiency"
* #8 "Perform an audiometry evaluation: every year until 6 years of age every 2 years until 12 years of age every 5 years thereafter. In addition, an otorhinolaryngological evaluation should be performed in case of tinnitus (ringing/whistling in the ear)." "Ear problems"
* #9 "Check blood glucose levels and glycosylated haemoglobin levels at least every 5 years." "Impaired glucose metabolism and diabetes melitus"
* #10 "Check total cholesterol, HDL, LDL and triglycerides levels (lipid profile) at least every 5 years." "Dyslipidemia"
* #11 "Check your weight and height and then calculate your BMI (body mass index) every 2 years (normal adult values 18.5-24.9)." "Overweight and obesity"
* #12 "Check blood pressure at least every 2 years and at every medical examination." "Hypertension"
* #13 "Maintain an adequate intake of calcium and vitamin D. Sunlight exposure and regular physical activity. Bone densitometry (DEXA) should be performed at least once. In prepubertal or pubertal children, consider postponing DEXA until the end of puberty. Report any persistent back pain and/or accidental fractures to your doctor." "Reduced bone mineral density"
* #14 "Report any persistent bone pain (particularly joint pain) to your doctor." "Osteonecrosis"
* #15 "Follow any indications already proposed by the endocrinologist; otherwise, perform an endocrinological examination as soon as possible." "Hypothalamic-pituitary (HP) axis problems (High risk) Growth hormone deficiency (GHD) TSH deficiency (TSHD) LH/FSH deficiency (LH/FSHD) ACTH deficiency (ACTHD)"
* #16 "In prepubertal period: Perform clinical check-up every 6 months to assess growth velocity and pubertal development. Measure fT4, TSH, and cortisol levels early in the morning every year; in case of lack of progression of pubertal development also check FSH and LH levels. In the post-pubertal period: - Perform a clinical check-up every year and in women also check the regularity of the menstrual cycle. - Check blood values of fT4, TSH, LH, FSH, iGF1 and cortisol early in the morning every year. - In men, also check total and free testosterone. - In women also check 17-beta estradiol Continue these check-ups for at least 15 years after diagnosis." "Hypothalamic-pituitary (HP) axis problems (Standard risk) Growth hormone deficiency (GHD) TSH deficiency (TSHD) LH/FSH deficiency (LH/FSHD) ACTH deficiency (ACTHD)"
* #17 "A clinical check-up for growth rate and pubertal development (tanner) should be peformed every 6 months until the age of 8." "Central precocious puberty (CPP) For girls with age below 8 years"
* #18 "Perform a clinical check-up every 6 months until the age of 9 to assess growth rate and pubertal development (tanner). Measure testosterone levels in the morning before 10:00 a.m. once a year until age 9." "Central precocious puberty (CPP) For boys with age below 9 yearss"
* #19 "Thyroid hormones (fT4 and TSH) should be tested at least once a year until the age of 18 and every 2-3 years after 18. If female, these tests should also be perform before and during pregnancy. In case of a total thyroidectomy, it is recommended to follow the endocrinologist's indications." "Thyroid function problems"
* #20 "Maintain a healthy lifestyle and alert your doctor immediately in case of sudden onset of neurological symptoms (e.g. acute and/or persistent headache, visual disturbances, strength deficit)" "Cerebrovascular problem"
* #21 "Pay attention to the following disorders: attention, language, learning, visual-motor coordination, memory or behavioural disorders. In these cases, perform a neuropsychological assessment." "Neurocognitive problems"
* #22 "Contact your doctor if you experience persistent pain, tingling, reduced strength and/or sensation in your limbs." "Peripheral neuropathy"
* #23 "Have an ophtalmological examination every 5 years" "Cataract"
* #24 "An ophtalmological examinationshould be performed at least every 5 years, and in case of eye dryness, pain or irritation and/or visual disturbances." "Eye problems"
* #25 "Perform a maxillofacial evaluation if there are any aesthetic or functional abnormalities of the head and/or face." "Craniofacial growth problems"
* #26 "Perform a clinical assessment of the spine at every medical evaluation and at least every year during pubertal development. Consult an orthopaedic specialist only if abnormalities are detected." "Spine scoliosis and kyphosis"
* #27 "Watch out for urinary symptoms (e.g. frequent urination, painful urination, urinary retention or blood in urine). If any of these symptoms occur, perform a urine test and urine culture and, if necessary, a urine cytology test. If the tests are pathological, a urological evaluation should be performed." "Lower urinary tract problems"
* #28 "Perform appropriate obstetrical follow-up in case of pregnancy," "Obstetric problems"
* #29 "Careful dental hygiene, and a dental examination in case of oral problems such as caries (tooth decay), abnormal tooth development or dry mouth." "Dental and oral problems"
* #30 "A gastroenterological evaluation should be performed in case of persistent abdominal symptoms such as abdominal pain, nausea, vomiting or bowel evacuation disorders." "Gastro-intestinal problems"
* #31 "Perform an ECG after the end of treatment and in any case repeat it after the age of 18, and perform a cardiological assessment if palpitations, dizziness and/or fainting/loss of consciousness occur." "Arrhythmia"
* #32 "Avoid active and passive smoking; Get annual flu and pneumococcal vaccines as indicated by your pediatrician/general practitioner; Perform a spirometry and carbon monoxide diffusion assessment (DLCO) at least once after the end of treatment and to be repeated in case of abnormalities; A clinical chest check-up must be performed by your pediatrician/ general practitioner at least every 5 years." "Pulmonary problems"
* #33 "Perform every 5 years: Urinalysis for creatinuria, proteinuria, glycosuria and phosphaturia; Blood test for creatinine, ionogram, albumin, and calculation of glomerular filtration rate (GFR)." "Renal problems (Glomerular dysfunction - Tubular dysfunction)"
* #34 "Regular clinical evaluation for signs and symptoms of liver dysfunction (e.g. hepatomegaly, spider nevi or pruritus). Transaminases, gammaGT and alkaline phosphatase should be measured at least once after treatment ends. In case of an increase in liver enzyme values: if between 1-2 times the normal value: repeat the test within 1 year. If more than 2 times the normal value: repeat the test within 2 months. In case of persistent liver abnormalities: Ask a hepatologist or gastroenterologist for further indications. If there is no obvious explanation (alcohol, medication, obesity) Avoid or use with caution potentially hepatotoxic drugs and supplements Consider immunisation against hepatitis A and B, if not already immune in case of chronic HBV / HCV infections discuss precautions to reduce viral transmission to family and sexual partners" "Liver problems"
* #35 "Perform the serum ferritin assay at least once after the end of treatment. Repeat test within 6 months if serum ferritin is above 500 ng/ml. In case of persistent hyperferritinemia, perform an MRI scan to quantify the iron content in the liver. If the latter is confirmed, ask a haematologist about the appropriate treatment (such as phlebotomy or chelation therapy)." "Iron overload"
* #36 "Complete the mandatory vaccination calendar and have pneumococcal, meningococcal and Haemophilus Influenzae vaccinations. Start broad-spectrum antibiotic therapy as soon as possible in case of: fever >38.3°C, animal bite with skin lesions, or other symptoms of severe infection (sepsis) such as cold/chills, low blood pressure, mental confusion and signs of rigidity. In such cases, blood count and blood culture should be performed immediately if possible. If travelling abroad, contact your local health authorities for information on the need for any prophylactic vaccinations." "Spleen problems"
* #37 "Genetic counselling (if not already performed) to determine any further screening tests." "Tumor predisposition"
* #38 "Protect yourself from the sun rays with highly protective sunscreen, especially on areas of the body that have been exposed to radiotherapy. Constantly check your skin paying attention to the appearance of new moles and/or changes in colour and size of those already present. Perform a dermatological check-up for mole mapping at least every 2 years." "Subsequent melanoma and non-melanoma skin cancer"
* #39 "Check for occult blood in stool every three years from the age of 30. If the test is positive, a colonoscopy should be performed." "Subsequent colorectal cancer"
* #40 "Have proper dental hygiene and pay attention to the appearance of any lesions inside the mouth." "Subsequent Oral Cancer"
* #41 "Check blood count in case of petechiae, intense pallor, persistent bone pain and/or fatigue." "Subsequent acute myeloid leukaemia or myelodysplasia"
* #42 "If there is blood in urine or burning sensation during urination, a cytological and chemical urinalysis should be performed. If pathological, perform a urological examination." "Subsequent bladder cancer"
* #43 "X-ray should be performed if swelling and/or persistent bone pain appears." "Subsequent Bone Cancer"
* #44 "Chest X-ray in case of persistent respiratory distress." "Subsequent lung cancer"
* #45 "Pay attention to the appearance of any neurological symptoms (e.g. persistent headache, visual disturbances, strength deficits) and report them to your doctor to discuss whether a neuro-radiological examination is necessary." "Subsequent CNS neoplasms"
* #46 "Perform: Cardiological examination at the end of treatment and every 5 years thereafter; Electrocardiogram (ECG) at the end of treatment, to be repeated at the age of 18 and cardiological evaluation in case of palpitations, dizziness and/or fainting/loss of consciousness. Echocardiogram 2 years after the end of treatment, to be repeated every 5 years; If female, echocardiogram in the first trimester of pregnancy." "Cardiac problems (Cardiomyopathy and/or Valvular disease and/or Cardiac ischemia)"
* #47 "Perform every 5 years: Urinalysis for creatinuria, proteinuria. Blood test for creatininemia and calculation of glomerular filtration rate (GFR). In case of nephrectomy, non-steroidal anti-inflammatory drugs should be used with caution." "Renal problems (Tubular dysfunction)"


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ValueSet: Recommendation
Id: vs-recommendation-eu-pcsp 
Title: "Recommendations"
Description: "Recommendations proposed by the PCSP algorithm"
//-------------------------------------------------------------------------------------------
* codes from system CsRecomandationPcsp
